spring.datasource.url=jdbc:postgresql://localhost:5432/market_users_db
spring.datasource.username=${MARKET_USER}
spring.datasource.password=${MARKET_PASS}

jwt.private-key-path=../certs/private.pem
jwt.public-key-path=../certs/public.pem
