spring.datasource.url=jdbc:postgresql://postgres:5432/market_users_db
spring.datasource.username=postgres
spring.datasource.password=password

jwt.private-key-path=/app/certs/private.pem
jwt.public-key-path=/app/certs/public.pem